package:
    name: ananse
    version: 0.1.4

build:
    skip: True # [py<35]

source:
    git_url: https://github.com/vanheeringen-lab/ANANSE.git

requirements:
    build:
        - python
    run:
        - python
        - "setuptools >= 0.7"
        - "numpy >= 1.18.1"
        - "scipy >= 0.9.0"
        - "matplotlib >= 2"
        - "jinja2"
        - "pyyaml >= 3.10"
        - "pybedtools"
        - "statsmodels"
        - "scikit-learn"
        - "sklearn-contrib-lightning >= 0.5.0"
        - "seaborn"
        - "pysam"
        - "xgboost >= 0.71"
        - "xdg"
        - "diskcache"
        - "xxhash"
        - "configparser"
        - "six"
        - "future"
        - "gimmemotifs >= 0.14.4"
        - "tqdm"
        - "pillow"
        - "networkx"
        - "chest" 
        - "dask"
        - "pytables" 
        - "adjusttext"
        - "genomepy >= 0.8.3"
        - "loguru"
        
about:
    home: https://github.com/vanheeringen-lab/ANANSE/
    license: MIT