package:
    name: ananse
    version: 0.1.1

build:
    skip: True # [py<35]

source:
    git_url: https://github.com/vanheeringen-lab/ANANSE.git

requirements:
    build:
        - python
    run:
        - python
        - "setuptools >=0.7"
        - "numpy"
        - "scipy >=0.9.0"
        - "matplotlib >=2"
        - "jinja2"
        - "pyyaml >=3.10"
        - "pybedtools"
        - "statsmodels"
        - "scikit-learn"
        - "sklearn-contrib-lightning"
        - "seaborn"
        - "pysam"
        - "xgboost >=0.71"
        - "xdg"
        - "diskcache"
        - "xxhash"
        - "configparser"
        - "six"
        - "future"
        - "gimmemotifs >=0.14.4"
        - "tqdm"
        - "pillow"
        - "networkx"
        - "chest" 
        - "dask"
        - "pytables" 
        - "adjusttext"
        
about:
    home: https://github.com/vanheeringen-lab/ANANSE/
    license: MIT