site_name: ANANSE
# theme: alabaster
theme: readthedocs

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
      - The easiest way to install: 'installation/#the-easiest-way-to-install'
      - Alternative installation: 'installation/#alternative-installation'
  - Input data: 'input_data.md'
      - Genome: 'input_data/#genome'
      - Motif database: 'input_data/#motif-database'
      - Enhancer data: 'input_data/#enhancer-data'
      - Expression data: 'input_data/#enhancer-data'
      - Differential expression data: 'input_data/#enhancer-data'
  - Command-line reference: 'command-line_reference.md'
      - List of tools
      - Input formats
      - Command: ananse binding: 'command-line_reference/#motif-database'
      - Command: ananse network: 'command-line_reference/#motif-database'
      - Command: ananse influence: 'command-line_reference/#motif-database'
  - API documentation: 'API_documentation.md'
      - Working with `binding` Class: 'API_documentation/#working-with-binding-class'
      - Working with `network` Class: 'API_documentation/#working-with-network-class'
      - Working with `influence` Class: 'API_documentation/#working-with-influence-class'
  - Examples: 'examples.md'
      - Command: ananse binding: 'examples/#motif-database'
      - Command: ananse network: 'examples/#motif-database'
      - Command: ananse influence: 'examples/#motif-database'
  - FAQ
      - Sorry, motif prediction tool X] is not supported
      - I get motifs that have differential scores in gimme maelstrom, however, the number is not different across clusters
      - I have upgraded GimmeMotifs and now it doesn’t find my genome
      - I cannot run gimme index anymore
      - I get a KeyError when running gimme maelstrom
  - Acknowledgments
