name: ananse_dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.7
  - setuptools >=0.7
  - adjusttext
  - dask
  - genomepy >=0.9.3
  - gimmemotifs >=0.15.1
  - loguru
  - matplotlib >=2
  - mosdepth  # TODO: still needed?
  - networkx
  - numpy
  - openpyxl
  - pandas=1.1.5  # tmp dependency due to gimmemotifs bug
  - pybedtools  # TODO: still needed?
  - pyranges
  - pysam  # TODO: still needed?
  - pytables  # required for pandas.read_hfd()
  - scikit-learn
  - scipy >=0.9.0
  - seaborn
  - sklearn-contrib-lightning
  - tqdm

  # Testing
  - black
  - flake8
  - flake8-bugbear
  - pytest
  - pytest-cov
