name: continuous-integration

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]  # [3.7, 3.8]
        os: [ubuntu-latest]  # [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - uses: conda-incubator/setup-miniconda@v2
#      with:
#        channels: conda-forge
#        auto-activate-base: true
#        activate-environment: ""
#    - name: Install dependencies 🔨
#      run: |
#        conda install conda-forge::mamba -y
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: bioconda,conda-forge,defaults
        channel-priority: true
        activate-environment: ananse_dev
        environment-file: requirements.yaml

#    - name: Install dependencies 🔨
#      run: |
#        python -m pip install --upgrade pip
#        pip install .
#        python -m pip install "dask[dataframe]"   # Install requirements for dask dataframe
#        pip install pyarrow                       # Install requirements for gimme motifs
#        apt-get install bedtools                  # Install requirements for pybedtools
#        pip install pytest                        # test related
#        pip install flake8 black                  # code quality related

    - name: Code formatting (black)
      if: always()
      run: |
        black --check ananse/enhancer_binding.py ananse/commands/enhancer_binding.py tests/

    - name: Code formatting (flake8)
      if: always()
      run: |
        flake8 ananse/enhancer_binding.py ananse/commands/enhancer_binding.py tests/

    - name: Run tests
      if: always()
      run: |
        pytest -vv --disable-pytest-warnings
