name: continuous-integration

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.8]  # [3.7, 3.8]
        os: [ubuntu-latest]  # [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - name: checkout 👀
      uses: actions/checkout@v2

    - name: Install dependencies 🔨
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: bioconda,conda-forge,defaults
        channel-priority: true
        activate-environment: ananse_dev
        environment-file: requirements.yaml

    - name: Code formatting (black) 🖤
      if: always()
      run: |
        black --check ananse/enhancer_binding.py ananse/commands/enhancer_binding.py tests/

    - name: Code formatting (flake8) 🎱
      if: always()
      run: |
        flake8 ananse/enhancer_binding.py ananse/commands/enhancer_binding.py tests/

    - name: Run tests 🧬
      if: always()
      run: |
        pytest -vv --disable-pytest-warnings
